name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Omni.CSS'e ilk kez katkıda bulunanlar için: İssue'lara göz atın veya pull request gönderin! Belge düzenlemek istiyorsanız, belge düzenleme kılavuzumuza bakın. Herhangi bir sorunuz varsa, bize bildirin!"
        pr-message: "Omni.CSS'e ilk kez katkıda bulunanlar için: İssue'lara göz atın veya pull request gönderin! Belge düzenlemek istiyorsanız, belge düzenleme kılavuzumuza bakın. Herhangi bir sorunuz varsa, bize bildirin!"
